name: Release Please
on:
  push:
    branches:
      - 'main'
      - '*.x'

# Documentation:
# https://github.com/googleapis/release-please
# https://github.com/googleapis/release-please-action
# https://github.com/googleapis/release-please/blob/main/docs/customizing.md

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          target-branch: ${{ github.ref_name }}
      - name: Release Info
        run: echo "$RELEASE_OUTPUT"
        env:
          RELEASE_OUTPUT: ${{ toJSON(steps.release.outputs) }}
      - name: 'Release: Determine version'
        id: version
        run: echo "version=$([[ "$VERSION" != "" ]] && echo "$VERSION" || echo "rev-$GITHUB_SHA")" >> $GITHUB_OUTPUT
        env:
          VERSION: ${{ steps.release.outputs.version }}
